version: '3'

services:
  reserv-app:
    build: ./reservapp-backEnd
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_HOST: jdbc:mysql://reserv_app:3306/reservapp?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      reserv_app:
        condition: service_healthy

  reserv_app:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: reservapp
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
